"""chat voice + guest push order_id

Revision ID: 01ddfe8099de
Revises: a766aacb1159
Create Date: 2026-07-31 15:22:07.376349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01ddfe8099de'
down_revision: Union[str, None] = 'a766aacb1159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audio_duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.String(length=32), nullable=True))
        batch_op.drop_constraint('uq_push_tokens_token', type_='unique')
        batch_op.create_index(batch_op.f('ix_push_tokens_order_id'), ['order_id'], unique=False)
        batch_op.create_unique_constraint('uq_push_tokens_token_order', ['token', 'order_id'])
        batch_op.create_foreign_key(
            'fk_push_tokens_order_id_orders', 'orders', ['order_id'], ['id'], ondelete='CASCADE'
        )

    # Composite UNIQUE(token, order_id) does NOT dedupe admin/customer rows
    # (order_id NULL, and NULLs are distinct in a unique index). A partial
    # unique index restores one-row-per-token for those. Created outside the
    # batch block so the WHERE clause survives on SQLite.
    op.create_index(
        'uq_push_tokens_token_null_order',
        'push_tokens',
        ['token'],
        unique=True,
        sqlite_where=sa.text('order_id IS NULL'),
        postgresql_where=sa.text('order_id IS NULL'),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_push_tokens_token_null_order', table_name='push_tokens')
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_push_tokens_order_id_orders', type_='foreignkey')
        batch_op.drop_constraint('uq_push_tokens_token_order', type_='unique')
        batch_op.drop_index(batch_op.f('ix_push_tokens_order_id'))
        batch_op.create_unique_constraint('uq_push_tokens_token', ['token'])
        batch_op.drop_column('order_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('audio_duration')
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
