"""settings table

Revision ID: db05da55d268
Revises: 01ddfe8099de
Create Date: 2026-08-07 10:36:23.224048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db05da55d268'
down_revision: Union[str, None] = '01ddfe8099de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
