"""order archived + chat image_url

Revision ID: e513810f9691
Revises: db05da55d268
Create Date: 2026-08-07 10:56:15.198439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e513810f9691'
down_revision: Union[str, None] = 'db05da55d268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
